apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: loadehcq8980-tenant-component
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: loadehcq8980-tenant-component
    app.kubernetes.io/part-of: loadehcq8980-tenant-app
  name: loadehcq8980-tenant-component
  namespace: loadehcq8980-tenant
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: loadehcq8980-tenant-component
    weight: null
status: {}
